### ISSUE TITLE
python preprocess.py

### ISSUE THREAD

**Issue by xizi** [jcjohnson/densecap#45]
$ python preprocess.py
There are 108077 images total
After filtering for splits there are 87396 images
adding images to hdf5.... (this might take a while)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/meituan/lishengxi/local_torch/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/meituan/lishengxi/local_torch/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "preprocess.py", line 246, in worker
    img = imread(filename)
  File "/home/sankuai/.local/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/meituan/lishengxi/local_torch/lib/python2.7/site-packages/PIL/Image.py", line 2280, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: 'data/visual-genome/images/53.jpg'
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/opt/meituan/lishengxi/local_torch/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/meituan/lishengxi/local_torch/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "preprocess.py", line 246, in worker
    img = imread(filename)
  File "/home/sankuai/.local/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/meituan/lishengxi/local_torch/lib/python2.7/site-packages/PIL/Image.py", line 2280, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: 'data/visual-genome/images/59.jpg'

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/opt/meituan/lishengxi/local_torch/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/meituan/lishengxi/local_torch/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "preprocess.py", line 246, in worker
    img = imread(filename)
  File "/home/sankuai/.local/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/meituan/lishengxi/local_torch/lib/python2.7/site-packages/PIL/Image.py", line 2280, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: 'data/visual-genome/images/54.jpg'

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/meituan/lishengxi/local_torch/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/meituan/lishengxi/local_torch/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "preprocess.py", line 246, in worker
    img = imread(filename)
  File "/home/sankuai/.local/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/meituan/lishengxi/local_torch/lib/python2.7/site-packages/PIL/Image.py", line 2280, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: 'data/visual-genome/images/51.jpg'

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/opt/meituan/lishengxi/local_torch/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/meituan/lishengxi/local_torch/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "preprocess.py", line 246, in worker
    img = imread(filename)
  File "/home/sankuai/.local/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/meituan/lishengxi/local_torch/lib/python2.7/site-packages/PIL/Image.py", line 2280, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: 'data/visual-genome/images/55.jpg'

hi, @jcjohnson why run the preprocess.py script produce above errors. 
The 53.jpg 59.jpg 54.jpg 55.jpg 51.jpg are not in path data/visual-genome/images

**Comment by xizi** [comment]
Is there some bugs in add_images(data, h5_file, args) function

**Comment by xizi** [comment]
or the densecap_splits.json is not compatible with visual genome dataset i download?

**Comment by puddinord** [comment]
hi，I came cross the same problem, how can fix it?
