### ISSUE TITLE
There is something wrong with the preprocess.py

### ISSUE THREAD

**Issue by yuxinWen** [jcjohnson/densecap#51]
It seems that there is something wrong with the hdf5.

There are 108077 images total
After filtering for splits there are 87398 images
Traceback (most recent call last):
  File "preprocess.py", line 470, in <module>
    main(args)
  File "preprocess.py", line 385, in main
    f = h5py.File(args.h5_output, 'w')
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 207, in __init__
    fid = make_fid(name, mode, userblock_size, fapl)
  File "/usr/lib/python2.7/dist-packages/h5py/_hl/files.py", line 85, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5f.pyx", line 90, in h5py.h5f.create (h5py/h5f.c:1984)
IOError: unable to create file (File accessibilty: Unable to open file)

How can I fix it? Thanks!

**Comment by yuxinWen** [comment]
Well, it seems that I didn't have the permission to write in the default direction. So I've solve the problem with root.
